In [ ]:
Q1. What is the mathematical formula for a linear SVM?

In [ ]:
Answer : The mathmatical formula for linear SVM is : y = w.x + b. here dot(.) between w and x represent vector dot product
         between them.

In [ ]:
Q2. What is the objective function of a linear SVM?

In [ ]:
Answer : The objective function of a linear Support Vector Machine (SVM) is formulated as a quadratic optimization problem.
         The goal is to find the parameters (weight vector w and bias term b) that define the hyperplane separating the data 
         while maximizing the margin and correctly classifying the training samples. The objective function is given by:
         Minimize Minimize : 0.5*(∥w∥**2)

In [ ]:
Q3. What is the kernel trick in SVM?

In [ ]:
Answer : The kernel trick is a technique used in Support Vector Machines (SVMs) to implicitly map input data into a higher-
         dimensional space without explicitly computing the transformed feature vectors. This is particularly useful when 
         the data is not linearly separable in its original feature space. The kernel trick allows SVMs to efficiently perform 
         computations in this higher-dimensional space without explicitly representing the transformed features.
            The idea behind the kernel trick lies in the choice of a kernel function. A kernel function computes the inner product 
        of the feature vectors in the transformed space without explicitly calculating the transformation. In other words, it
        allows SVMs to operate in a higher-dimensional space without the need to compute and store the transformed feature 
        vectors.

In [ ]:
Q4. What is the role of support vectors in SVM Explain with example ?

In [ ]:
Answer : Support vectors play a crucial role in Support Vector Machines (SVMs). In the context of SVM, support vectors are the 
        data points that lie closest to the decision boundary (hyperplane) and have a direct influence on its position and 
        orientation. These are the instances that are most critical for determining the optimal hyperplane that maximizes the 
        margin between classes.

      The support vectors are the data points that have non-zero values for the Lagrange multipliers (ai) in the SVM optimization
      problem. These Lagrange multipliers are associated with the margin constraints and determine the importance of individual
      data points in the decision function. Support vectors are the ones that essentially "support" the decision boundary; if you
      remove any other data points, the position of the hyperplane may not change, but removing a support vector could lead to a
      different decision boundary.

    Here's a simple example to illustrate the role of support vectors:
    Suppose you have a 2D dataset with two classes (positive and negative), and the SVM aims to find a linear decision boundary.
    The decision boundary is determined by a hyperplane, and the support vectors are the data points that lie on the margins or 
    have the smallest margin to the decision boundary.
    
    In the example above, the circles represent positive class samples, and the crosses represent negative class samples. The 
    solid line represents the optimal hyperplane, and the dashed lines represent the margins. The support vectors are the data 
    points that lie on the margins or inside the margin. In this case, the support vectors are the points marked with larger 
    circles and crosses.

In [ ]:
Q5. Illustrate with examples and graphs of Hyperplane, Marginal plane, Soft margin and Hard margin in SVM?

In [ ]:
Answer :
1.Hyperplane :The hyperplane is the decision boundary that separates data points of different classes. In a 2D space,it's a line.
In this example, the hyperplane (solid line) separates the positive (circles) and negative (crosses) class points.

2.Marginal Plane: The marginal plane consists of the two dashed lines parallel to the hyperplane, creating a margin between them.
The margin is the distance between the hyperplane and the marginal plane. The marginal plane includes the dashed lines representing
the margin. Support vectors are the points lying on or inside these marginal lines.

3.Hard Margin: In a hard margin SVM, the goal is to find a hyperplane with the maximum margin that perfectly separates the classes.
No data points are allowed to violate the margin. In this case, the margin is maximized, and all support vectors lie on the margins.
There's no tolerance for misclassification.

4. Soft Margin: In a soft margin SVM, a certain degree of misclassification is tolerated to achieve a more robust model, especially
in the presence of outliers. In this example, a few points are allowed to fall inside the margin or even on the wrong side of the 
decision boundary. This flexibility improves the model's ability to generalize to unseen data but introduces a trade-off between a
wider margin and the acceptance of some misclassifications.

In [ ]:
Q6. SVM Implementation through Iris dataset.
~ Load the iris dataset from the scikit-learn library and split it into a training set and a testing setl
~ Train a linear SVM classifier on the training set and predict the labels for the testing setl
~ Compute the accuracy of the model on the testing setl
~ Plot the decision boundaries of the trained model using two of the featuresl
~ Try different values of the regularisation parameter C and see how it affects the performance of
the model.

In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset = load_iris()

In [5]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.DataFrame(dataset.data, columns = dataset.feature_names)

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
df['Target'] = dataset.target

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
X = df.iloc[:,:-1]

In [14]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [15]:
Y = df['Target']

In [16]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Target, Length: 150, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.25, random_state = 42)

In [23]:
from sklearn.svm import SVC

In [24]:
svc = SVC()

In [25]:
svc.fit(x_train, y_train)

SVC()

In [28]:
y_pred = svc.predict(x_test)

In [29]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [35]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [36]:
accuracy_score(y_test, y_pred)

1.0

In [37]:
confusion_matrix(y_test, y_pred)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [39]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

